### ISSUE TITLE
arbitrary depth

### ISSUE THREAD

**Issue by 89z** [thejerf/cm#1]
I see MapMapMap

https://pkg.go.dev/github.com/thejerf/cm#MapMapMap

does that mean that maps dont support arbitrary depth? What if user needs Map*10?

**Comment by thejerf** [comment]
The API I wrote here can not support arbitrary depth because there is no way for a function like Get to fetch an arbitrary number of generically-typed arguments.

You can write something that recurses, but you end up with some fairly unpleasant types. A ten-level map would have to be `Map[Type1, Map[Type2, Map[Type3, Map[Type4, Map[Type5, Map[Type6, Map[Type7, Map[Type8, Map[Type9, Map[Type10, Type11]]]]]]]]]]`. Similarly, you can't easily get the tuple types coming out of that, though you can get the KeyTree.

If you chart the map levels, the vast majority are one-level maps (as provided by Go), the vast majority of the remainder are two, the vast majority of the remainder are three, and by now we're down to a use case so small I'm not too worried about it. I'd rather have a nice API for the 2 & 3 levels than an infinite recursively.

**Comment by 89z** [comment]
> there is no way for a function like Get to fetch an arbitrary number of generically-typed arguments

Um yeah, thats not true:

~~~go
package deep

type object map[string]any

type token[T any] struct {
   object
   value T
}

func newToken[T any](m object) token[T] {
   return token[T]{object: m}
}

func (t token[T]) get(key string) token[T] {
   switch val := t.object[key].(type) {
   case object:
      t.object = val
   case T:
      t.value = val
   }
   return t
}
~~~

**Comment by thejerf** [comment]
I am not interested in an API that looks like `.Get(token[Key1, token[Key2, token[Key3, Val]]]{key1, token[Key2, token[Key3, Val]]{key2, token[Key3, Val]{key3, nil}}}})` or whatever to retrieve a fixed value from the map versus `.Get(key1, key2, key3)`.

I haven't played with this enough to know off the top of my head whether Go will infer the middle generic types, but even if it's just `.Get(token[Key1, token[Key2, token[Key3, Val]]]{key1, {key2, {key3, nil}}}}` or whatever, it is already more than I'm interested in.

The goal of this package isn't an abstract exercise in type recursion just because Go can do a bit more now than it used to. The goal of this package is to _make using multilevel maps easier_.

I am unsure what your goal is here. If you want recursive maps, you've clearly got the chops to implement them. So go for it. This package is permissively licensed, you can take whatever you like from it, which probably won't be much in the end except maybe the test suite, but hey, it's there.

**Comment by 89z** [comment]
> I am not interested in an API that looks like `.Get(token[Key1, token[Key2, token[Key3, Val]]]{key1, token[Key2, token[Key3, Val]]{key2, token[Key3, Val]{key3, nil}}}})` or whatever to retrieve a fixed value from the map versus `.Get(key1, key2, key3)`.

Here is an example use of the code above:

~~~go
package main

func main() {
   obj := object{
      "one": object{
         "two": object{"three": 3},
      },
   }
   tok := token[int]{object: obj}
   three := tok.get("one").get("two").get("three")
   println(three.value == 3)
}
~~~

looks pretty simple to me...

**Comment by thejerf** [comment]
So, one productive side effect of this discussion is that I've removed .Get entirely. It turns out to be useless. A side effect of my doing this project has been to really nail down what zero values do in Go. Even after years of usage I still had some fuzziness.

It turns out the correct spelling for .Get `mm["one"]["two"]["three"]` anyhow.

**Comment by 89z** [comment]
in my case, the keys are a fixed type. could be string, could be number, but the keys will always be the same type. Similar to JSON, where the keys are always string, but the value can be anything.
